export const types = {
  CREATE_PROFILE_START: "CREATE_PROFILE_START",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",
  ////////////////
  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
  //
  LOAD_PROFILE_START: "LOAD_PROFILE_START",
  LOAD_PROFILE_SUCCESS: "LOAD_PROFILE_SUCCESS",
  LOAD_PROFILE_FAILURE: "LOAD_PROFILE_FAILURE",
  //
  ADDING_PROFILE_START: "ADDING_PROFILE_START",
  ADDING_PROFILE_SUCCESS: "ADDING_PROFILE_SUCCESS",
  ADDING_PROFILE_FAILURE: "ADDING_PROFILE_FAILURE",
  //
  DELETE_PROFILE_START: "DELETE_PROFILE_START",
  DELETE_PROFILE_SUCCESS: "DELETE_PROFILE_SUCCESS",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",
  // @EXPERICNE
  ADD_EXPERIENCE_START: "ADD_EXPERIENCE_START",
  ADD_EXPERIENCE_SUCCESS: "ADD_EXPERIENCE_SUCCESS",
  ADD_EXPERIENCE_FAILURE: "ADD_EXPERIENCE_FAILURE",
  //
  DELETE_EXPERIENCE_START: "DELETE_EXPERIENCE_START",
  DELETE_EXPERIENCE_SUCCESS: "DELETE_EXPERIENCE_SUCCESS",
  DELETE_EXPERIENCE_FAILURE: "DELETE_EXPERIENCE_FAILURE",
  // @Education
  ADD_EDUCATION_START: "ADD_EDUCATION_START",
  ADD_EDUCATION_SUCCESS: "ADD_EDUCATION_SUCCESS",
  ADD_EDUCATION_FAILURE: "ADD_EDUCATION_FAILURE",
  //
  DELETE_EDUCATION_START: "DELETE_EDUCATION_START",
  DELETE_EDUCATION_SUCCESS: "DELETE_EDUCATION_SUCCESS",
  DELETE_EDUCATION_FAILURE: "DELETE_EDUCATION_FAILURE",
  //
  UPLOAD_PHOTO_START: "UPLOAD_PHOTO_START",
  UPLOAD_PHOTO_SUCCESS: "UPLOAD_PHOTO_SUCCESS",
  UPLOAD_PHOTO_FAILURE: "UPLOAD_PHOTO_FAILURE",
  // company profile
  CREATE_COMPANY_START: "CREATE_COMPANY_START",
  CREATE_COMPANY_SUCCESS: "CREATE_COMPANY_SUCCESS",
  CREATE_COMPANY_FAILURE: "CREATE_COMPANY_FAILURE",
  //  load company profile
  LOAD_COMPANY_START: "LOAD_COMPANY_START",
  LOAD_COMPANY_SUCCESS: "LOAD_COMPANY_SUCCESS",
  LOAD_COMPANY_FAILURE: "LOAD_COMPANY_FAILURE",
  //
  UPDATE_COMPANY_START: "UPDATE_COMPANY_START",
  UPDATE_COMPANY_FAILURE: "UPDATE_COMPANY_SUCCESS",
};
