export const types = {
  ADD_JOB_START: "ADD_JOB_START",
  ADD_JOB_SUCCESS: "ADD_JOB_SUCCESS",
  ADD_JOB_FAILURE: "ADD_JOB_FAILURE",
  GET_SINGLE_JOB_START: "GET_SINGLE_JOB_START",
  GET_SINGLE_JOB_SUCCESS: "GET_SINGLE_JOB_SUCCESS",
  GET_SINGLE_JOB_FAILURE: "GET_SINGLE_JOB_FAILURE",
  //
  FETCH_ALL_JOBS_START: "FETCH_ALL_JOBS_START",
  FETCH_ALL_JOBS_SUCCESS: "FETCH_ALL_JOBS_SUCCESS",
  FETCH_ALL_JOBS_FAILURE: "FETCH_ALL_JOBS_FAILURE",
  UPDATE_JOB_START: "UPDATE_JOB_START",
  UPDATE_JOB_SUCCESS: "UPDATE_JOB_SUCCESS",
  UPDATE_JOB_FAILURE: "UPDATE_JOB_FAILURE",
};
