export const types = {
  // company profile
  CREATE_COMPANY_START: "CREATE_COMPANY_START",
  CREATE_COMPANY_SUCCESS: "CREATE_COMPANY_SUCCESS",
  CREATE_COMPANY_FAILURE: "CREATE_COMPANY_FAILURE",
  //  load company profile
  LOAD_COMPANY_START: "LOAD_COMPANY_START",
  LOAD_COMPANY_SUCCESS: "LOAD_COMPANY_SUCCESS",
  LOAD_COMPANY_FAILURE: "LOAD_COMPANY_FAILURE",
  //
  UPDATE_COMPANY_START: "UPDATE_COMPANY_START",
  UPDATE_COMPANY_FAILURE: "UPDATE_COMPANY_SUCCESS",
  EDIT_PROFILE_START: "EDIT_PROFILE_START",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE: "EDIT_PROFILE_FAILURE",
};
